
spring:
  application:
    name: msa-user-api-test
  profiles:
    group:
      local: local
default:
  string: default property

---
spring:
  config.activate.on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/docs/**
    web:
      resources:
        static-locations: classpath:/static/docs
        add-mappings: true
  datasource:
    write:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3305/msa_test
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    read:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3305/msa_test
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}